sugarcube-2:
  macros:
    regionmap:
      name: regionmap
      container: true
    regionnames:
      name: regionnames
    regionrose:
      name: regionrose
      container: true
    onattempt:
      name: onattempt
    abort:
      name: abort
    disable:
      name: disable
    onabort:
      name: onabort
    onenter:
      name: onenter
    rosedisable:
      name: rosedisable
    roseenable:
      name: roseenable
    areamap:
      name: areamap
      container: true
    variables:
      name: variables
    areavars:
      name: areavars
    mapvars:
      name: mapvars
    createmap:
      name: createmap
      container: true
    newrose:
      name: newrose
      container: true
    newmap:
      name: newmap
      container: true
    showrose:
      name: showrose
    maptiles:
      name: maptiles
    newnav:
      name: newnav
      container: true
    mapstart:
      name: mapstart
    showmap:
      name: showmap
    maptile:
      name: maptile
      container: true
    tiletype:
      name: tiletype
    tileelement:
      name: tileelement
    shownav:
      name: shownav
      container: true
    deletenpc:
      name: deletenpc
    addplayer:
      name: addplayer
      container: true
    deleteobject:
      name: deleteobject
    moveobject:
      name: moveobject
    defineplayer:
      name: defineplayer
      container: true
    newobject:
      name: newobject
      container: true
    setplayer:
      name: setplayer
    newtile:
      name: newtile
      container: true
    newentity:
      name: newentity
      container: true
    entityhandler:
      name: entityhandler
    mapzoom:
      name: mapzoom
